# Generated by Django 4.2.30 on 2026-05-13 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="shortenedurl",
            name="max_clicks",
            field=models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
        ),
        migrations.AddField(
            model_name="shortenedurl",
            name="password_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(
                fields=["shortened_url", "-clicked_at"],
                name="shortener_c_shorten_7d1f9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shortenedurl",
            index=models.Index(
                fields=["custom_alias"], name="shortener_s_custom__bb8238_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shortenedurl",
            index=models.Index(
                fields=["user", "-created_at"], name="shortener_s_user_id_ef3a4c_idx"
            ),
        ),
    ]
